version: '2.2'
services:
  db:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_api
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata

    ports:
      - '5432:5432'

  app_restapi:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
